# NOTE: update this with your service name
service: serverless-rest-rds-starterkit

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    DB_USERNAME_MASTER: ${env:DB_USERNAME_MASTER}
    DB_PASSWORD_MASTER: ${env:DB_PASSWORD_MASTER}
    DB_DATABASE_MASTER: ${env:DB_DATABASE_MASTER}
    DB_HOST_MASTER: ${env:DB_HOST_MASTER}

  vpc:
    securityGroupIds:
      - sg-xxxxxxx
    subnetIds:
      - subnet-xxxxxx
      - subnet-xxxxxx
      - subnet-xxxxxx

functions:
  addTeam:
    handler: src/services/addTeam.addTeam
    events:
      - http:
          path: addTeam
          method: post

custom:
  bundle:
    ignorePackages:
      - pg-native
